# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

center <- function(M, w, N) {
    .Call('_aftosmac_center', PACKAGE = 'aftosmac', M, w, N)
}

km <- function(e, d, p) {
    .Call('_aftosmac_km', PACKAGE = 'aftosmac', e, d, p)
}

gehan_ns <- function(x, y, d, beta, p, n) {
    .Call('_aftosmac_gehan_ns', PACKAGE = 'aftosmac', x, y, d, beta, p, n)
}

gehan_mtg <- function(x, d, e, ind) {
    .Call('_aftosmac_gehan_mtg', PACKAGE = 'aftosmac', x, d, e, ind)
}

gehan_smth <- function(x, y, d, p, b, n) {
    .Call('_aftosmac_gehan_smth', PACKAGE = 'aftosmac', x, y, d, p, b, n)
}

gehan_s_mtg <- function(x, y, d, p, bt, ind, n) {
    .Call('_aftosmac_gehan_s_mtg', PACKAGE = 'aftosmac', x, y, d, p, bt, ind, n)
}

gehan_s_jaco <- function(x, y, d, p, b, n) {
    .Call('_aftosmac_gehan_s_jaco', PACKAGE = 'aftosmac', x, y, d, p, b, n)
}

